"""One-figure summary of what the physics-informed models prove, and what they do not.

Four separate PINN studies each answer one question, and the answers only make
sense together: embedding the governing equations buys hidden states and energy
closure that curve fitting cannot supply; that advantage survives a truth built
on a different discretization; but a converged-looking loss does not mean the
physics converged, and a good fit cannot tell you the data were sufficient.

Every value is read from the four published figure sidecars. Nothing is
retrained or recomputed, and no existing artifact is replaced.
"""

import argparse
import json
from pathlib import Path
from typing import Any, Mapping, NamedTuple, Sequence

from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure
from matplotlib.lines import Line2D

from .paths import default_figure_path, save_figure_data, save_figure_explanation


WALKTHROUGH = "PINN_EVIDENCE_SUMMARY.md"

DEFAULT_PINN_TRUST_PATH = default_figure_path(
    "pinn_trust_and_limits.png", WALKTHROUGH
)

SOURCE_FIGURES = {
    "reconstruction": (
        "forward_reconstruction_comparison.json",
        "FORWARD_RECONSTRUCTION_COMPARISON.md",
    ),
    "mismatch": (
        "distributed_independent_validation.json",
        "DISTRIBUTED_INDEPENDENT_VALIDATION.md",
    ),
    "audit": (
        "distributed_pinn_training_audit.json",
        "DISTRIBUTED_PINN_TRAINING_AUDIT.md",
    ),
    "sufficiency": (
        "distributed_observation_identifiability.json",
        "DISTRIBUTED_OBSERVATION_IDENTIFIABILITY.md",
    ),
}

FIGURE_EXPLANATION = (
    "This figure combines four physics-informed studies into one argument. It "
    "contrasts a physics-informed and a data-only network of identical size on "
    "the same incomplete measurements, compares inverse estimators against a "
    "truth generated by a different discretization and property basis, tracks "
    "whether a falling loss actually means the governing residual converged, "
    "and shows that post-fit quality cannot detect an observation set that "
    "does not identify the property curve. Every value is read from the four "
    "published sidecars; nothing is retrained."
)

PHYSICS, DATA_ONLY, CONVENTIONAL = "#087F8C", "#D46A34", "#5266A3"
ACCENT = "#8E44AD"
INK, MUTED, RULE, GRID = "#192C40", "#64748B", "#CBD5E1", "#E2E8F0"

RECONSTRUCTION_METRICS = (
    ("mean_training_seconds", "Training time"),
    ("mean_retained_noisy_observation_rmse", "Fit to the noisy rows\nit was given"),
    ("mean_retained_truth_rmse", "Truth under those rows"),
    ("mean_missing_exchanger_rmse", "Sensor gap"),
    ("mean_energy_rate_closure_rms", "Whole-system\nenergy closure"),
    ("mean_hidden_face_rmse", "Never-measured\nfaces"),
)

ESTIMATOR_LABELS = {
    "pinn_unregularized": ("Inverse PINN", PHYSICS),
    "pinn_matched": ("Inverse PINN\n+ matched prior", PHYSICS),
    "conventional_unregularized": ("Conventional fit", CONVENTIONAL),
    "conventional_matched": ("Conventional fit\n+ matched prior", CONVENTIONAL),
}

CASE_LABELS = {
    "full_bidirectional": "Zero, positive and\nnegative current\n+ voltage",
    "zero_current_only": "Passive relaxation\nonly",
    "positive_temperature_only": "Positive current,\nface temperatures",
    "positive_temperature_voltage": "Positive current,\ntemperatures\n+ voltage",
}


class ReconstructionRatio(NamedTuple):
    metric: str
    label: str
    physics_value: float
    data_only_value: float
    ratio: float


class MismatchSummary(NamedTuple):
    name: str
    label: str
    success_count: int
    completed_count: int
    property_relative_rmse: float


class AuditPoint(NamedTuple):
    epoch: int
    amplitude_ratio: float
    physics_residual_ratio: float
    observation_loss: float
    operationally_acceptable_count: int
    shape_recovered_count: int
    completed_count: int


class SufficiencyCase(NamedTuple):
    name: str
    label: str
    supported_rank: int
    coefficient_count: int
    status: str
    permitted: bool
    pinn_property_relative_rmse: float | None
    conventional_property_relative_rmse: float | None


class PinnTrustStory(NamedTuple):
    trainable_parameters: int
    retained_observations: int
    removed_observations: int
    reconstruction_trials: int
    physics_advantage_trials: int
    ratios: tuple[ReconstructionRatio, ...]
    mismatch_trials: int
    mismatch: tuple[MismatchSummary, ...]
    audit: tuple[AuditPoint, ...]
    audit_trials: int
    maximum_physics_residual_ratio: float
    sufficiency: tuple[SufficiencyCase, ...]


def _load(path: Path | str) -> Mapping[str, Any]:
    resolved = Path(path).expanduser().resolve()
    with resolved.open(encoding="utf-8") as stream:
        payload = json.load(stream)
    data = payload.get("data")
    if not isinstance(data, Mapping):
        raise ValueError(f"{resolved} is not a figure sidecar")
    return data


def _mean_property_rmse(fits: Sequence[Mapping[str, Any]], estimator: str) -> float | None:
    values = [
        item["property_relative_rmse"]
        for item in fits
        if item["estimator"] == estimator
    ]
    return sum(values) / len(values) if values else None


def build_pinn_trust_story(
    reconstruction: Mapping[str, Any],
    mismatch: Mapping[str, Any],
    audit: Mapping[str, Any],
    sufficiency: Mapping[str, Any],
) -> PinnTrustStory:
    """Assemble the four published PINN results into one comparison."""

    by_method = {item["method"]: item for item in reconstruction["summaries"]}
    physics = by_method["physics_informed"]
    data_only = by_method["data_only"]
    ratios = tuple(
        ReconstructionRatio(
            metric=key,
            label=label,
            physics_value=physics[key],
            data_only_value=data_only[key],
            ratio=data_only[key] / physics[key],
        )
        for key, label in RECONSTRUCTION_METRICS
    )
    mismatch_summaries = tuple(
        MismatchSummary(
            name=item["name"],
            label=ESTIMATOR_LABELS[item["name"]][0],
            success_count=item["success_count"],
            completed_count=item["completed_count"],
            property_relative_rmse=item["mean_in_support_property_relative_rmse"],
        )
        for item in mismatch["summaries"]
    )
    audit_points = tuple(
        AuditPoint(
            epoch=item["epoch"],
            amplitude_ratio=item["mean_amplitude_ratio"],
            physics_residual_ratio=item["mean_physics_residual_ratio"],
            observation_loss=item["mean_observation_loss"],
            operationally_acceptable_count=item["operationally_acceptable_count"],
            shape_recovered_count=item["shape_recovered_count"],
            completed_count=item["completed_count"],
        )
        for item in sorted(audit["epoch_summaries"], key=lambda item: item["epoch"])
    )
    cases = []
    for case in sufficiency["cases"]:
        name = case["definition"]["name"]
        fits = case.get("fits", ())
        cases.append(
            SufficiencyCase(
                name=name,
                label=CASE_LABELS.get(name, name),
                supported_rank=case["assessment"]["supported_rank"],
                coefficient_count=case["assessment"]["coefficient_count"],
                status=case["assessment"]["status"],
                permitted=bool(
                    fits and all(item["permitted_by_prefit_gate"] for item in fits)
                ),
                pinn_property_relative_rmse=_mean_property_rmse(fits, "pinn"),
                conventional_property_relative_rmse=_mean_property_rmse(
                    fits, "conventional"
                ),
            )
        )
    return PinnTrustStory(
        trainable_parameters=reconstruction["trainable_parameter_count_per_model"],
        retained_observations=reconstruction["retained_observation_count"],
        removed_observations=reconstruction["removed_observation_count"],
        reconstruction_trials=physics["trial_count"],
        physics_advantage_trials=reconstruction["physics_all_metric_advantage_count"],
        ratios=ratios,
        mismatch_trials=mismatch["config"]["trial_count"],
        mismatch=mismatch_summaries,
        audit=audit_points,
        audit_trials=audit["config"]["trial_count"],
        maximum_physics_residual_ratio=audit["config"]["maximum_physics_residual_ratio"],
        sufficiency=tuple(cases),
    )


def format_pinn_trust_report(story: PinnTrustStory) -> str:
    """Return the plain-text version of the combined PINN argument."""

    lines = [
        "Physics-informed models: what they prove and what they do not",
        "=============================================================",
        "",
        "1 - Matched networks on the same incomplete data "
        f"({story.trainable_parameters} parameters each, "
        f"{story.retained_observations} noisy rows, "
        f"{story.removed_observations} removed):",
    ]
    for ratio in story.ratios:
        better = "data-only better" if ratio.ratio < 1.0 else "physics better"
        lines.append(
            f"  {ratio.label.replace(chr(10), ' ')}: physics={ratio.physics_value:.6g}; "
            f"data-only={ratio.data_only_value:.6g}; ratio={ratio.ratio:.3g}x "
            f"({better})"
        )
    lines.append(
        f"  physics wins every metric in "
        f"{story.physics_advantage_trials}/{story.reconstruction_trials} trials"
    )
    lines.extend(
        ("", f"2 - Independent truth, {story.mismatch_trials} paired noisy trials:")
    )
    for item in story.mismatch:
        lines.append(
            f"  {item.label.replace(chr(10), ' ')}: passes "
            f"{item.success_count}/{item.completed_count}; "
            f"property RMSE={100 * item.property_relative_rmse:.2f}%"
        )
    lines.extend(("", f"3 - Training audit, {story.audit_trials} seeds per epoch budget:"))
    for point in story.audit:
        lines.append(
            f"  epoch {point.epoch}: curve amplitude="
            f"{100 * point.amplitude_ratio:.1f}% of truth; "
            f"physics residual ratio={100 * point.physics_residual_ratio:.1f}%; "
            f"observation loss={point.observation_loss:.4f}; "
            f"operational gate={point.operationally_acceptable_count}/"
            f"{point.completed_count}; curve shape="
            f"{point.shape_recovered_count}/{point.completed_count}"
        )
    lines.extend(("", "4 - Observation sufficiency before fitting:"))
    for case in story.sufficiency:
        rendered = (
            f"{100 * case.pinn_property_relative_rmse:.2f}%"
            if case.pinn_property_relative_rmse is not None
            else "no fit attempted"
        )
        lines.append(
            f"  {case.label.replace(chr(10), ' ')}: supported rank="
            f"{case.supported_rank}/{case.coefficient_count}; {case.status}; "
            f"prefit gate={'permitted' if case.permitted else 'rejected'}; "
            f"PINN post-fit property RMSE={rendered}"
        )
    lines.extend(
        (
            "",
            "Interpretation boundary:",
            "  All four studies are synthetic. Panels 2 to 4 share the continuum",
            "  equations with their truth even when the discretization differs,",
            "  so none of this is hardware identifiability.",
            "  Panel 1 compares one physics-informed against one data-only network",
            "  of identical size; it is not a general statement about architectures.",
            "  Values are read from stored sidecars; nothing is retrained.",
        )
    )
    return "\n".join(lines)


def _style_axis(axis) -> None:
    axis.spines[["top", "right"]].set_visible(False)
    for side in ("bottom", "left"):
        axis.spines[side].set_color(RULE)
    axis.tick_params(colors=MUTED, labelsize=10.5, length=0, pad=8)
    axis.grid(color=GRID, linewidth=0.8)
    axis.set_axisbelow(True)
    for label in (axis.xaxis.label, axis.yaxis.label):
        label.set_color(MUTED)
        label.set_size(11)


def _heading(axis, title: str, detail: str) -> None:
    axis.text(0, 1.20, title, transform=axis.transAxes,
              fontsize=15, fontweight="bold", color=INK)
    axis.text(0, 1.08, detail, transform=axis.transAxes,
              fontsize=10.5, color=MUTED)


def _plot_reconstruction(axis, story: PinnTrustStory) -> None:
    ordered = sorted(story.ratios, key=lambda item: item.ratio)
    positions = range(len(ordered))
    colors = [PHYSICS if item.ratio > 1.0 else DATA_ONLY for item in ordered]
    for position, item, color in zip(positions, ordered, colors):
        axis.plot((1.0, item.ratio), (position, position),
                  color=color, linewidth=2.0, alpha=0.55, zorder=1)
        axis.plot(item.ratio, position, marker="o", markersize=9, color=color,
                  markeredgecolor="white", markeredgewidth=0.7, zorder=3)
        axis.annotate(
            f"{item.ratio:.2f}x" if item.ratio < 10 else f"{item.ratio:.0f}x",
            (item.ratio, position), xytext=(0, 11), textcoords="offset points",
            ha="center", color=color, fontsize=10,
        )
    axis.axvline(1.0, color=MUTED, linestyle="--", linewidth=1.2)
    axis.set_xscale("log")
    axis.set_yticks(positions, [item.label for item in ordered])
    axis.set_ylim(-0.7, len(ordered) - 0.25)
    axis.grid(axis="y", visible=False)
    axis.set_xlabel("Data-only error / physics-informed error")
    axis.text(0.82, len(ordered) - 0.6, "data-only better", color=DATA_ONLY,
              fontsize=9.5, ha="right")
    axis.text(1.25, len(ordered) - 0.6, "physics-informed better", color=PHYSICS,
              fontsize=9.5)


def _plot_mismatch(axis, story: PinnTrustStory) -> None:
    order = (
        "conventional_unregularized", "conventional_matched",
        "pinn_unregularized", "pinn_matched",
    )
    lookup = {item.name: item for item in story.mismatch}
    for position, name in enumerate(order):
        item = lookup[name]
        color = ESTIMATOR_LABELS[name][1]
        value = 100 * item.property_relative_rmse
        axis.plot((0, value), (position, position), color=color,
                  linewidth=2.0, alpha=0.55, zorder=1)
        axis.plot(value, position, marker="o", markersize=9, color=color,
                  markeredgecolor="white", markeredgewidth=0.7, zorder=3)
        axis.annotate(
            f"{value:.2f}%   passes {item.success_count}/{item.completed_count}",
            (value, position), xytext=(11, -3), textcoords="offset points",
            color=color, fontsize=10,
        )
    axis.set_yticks(range(len(order)), [ESTIMATOR_LABELS[n][0] for n in order])
    axis.set_xlim(0, 14.5)
    axis.set_ylim(-0.6, len(order) - 0.4)
    axis.grid(axis="y", visible=False)
    axis.set_xlabel("Property-curve error against independent truth (%)")


def _plot_audit(axis, story: PinnTrustStory) -> None:
    epochs = [point.epoch for point in story.audit]
    positions = range(len(epochs))
    series = (
        ("Curve amplitude vs truth", [p.amplitude_ratio for p in story.audit],
         PHYSICS, "o", "-"),
        ("Physics residual ratio", [p.physics_residual_ratio for p in story.audit],
         ACCENT, "s", "-"),
        ("Observation loss", [p.observation_loss for p in story.audit],
         DATA_ONLY, "^", "--"),
    )
    for label, values, color, marker, linestyle in series:
        axis.plot(positions, values, color=color, marker=marker, markersize=8,
                  linewidth=2.0, linestyle=linestyle, label=label,
                  markeredgecolor="white", markeredgewidth=0.7)
    axis.axhline(1.0, color=MUTED, linestyle=":", linewidth=1.1)
    axis.axhline(story.maximum_physics_residual_ratio, color=ACCENT,
                 linestyle=":", linewidth=1.1)
    axis.text(len(epochs) - 0.55, story.maximum_physics_residual_ratio + 0.03,
              "residual gate", color=ACCENT, fontsize=9, ha="right")
    axis.text(len(epochs) - 0.55, 1.03, "truth amplitude", color=MUTED,
              fontsize=9, ha="right")
    for position, point in zip(positions, story.audit):
        axis.annotate(
            f"operational {point.operationally_acceptable_count}/"
            f"{point.completed_count}\nshape "
            f"{point.shape_recovered_count}/{point.completed_count}",
            (position, 0.02), xytext=(0, 0), textcoords="offset points",
            ha="center", va="bottom", color=MUTED, fontsize=9,
        )
    axis.set_xticks(positions, [f"{value:,}" for value in epochs])
    axis.set_xlim(-0.35, len(epochs) - 0.3)
    axis.set_ylim(0, 1.8)
    axis.grid(axis="x", visible=False)
    axis.set_xlabel("Training epochs")
    axis.set_ylabel("Ratio to target")
    axis.legend(loc="upper left", frameon=False, fontsize=9.5, ncol=1,
                bbox_to_anchor=(0.0, 1.02))


def _plot_sufficiency(axis, story: PinnTrustStory) -> None:
    order = (
        "full_bidirectional", "positive_temperature_voltage",
        "positive_temperature_only", "zero_current_only",
    )
    lookup = {case.name: case for case in story.sufficiency}
    labels = []
    for position, name in enumerate(order):
        case = lookup[name]
        labels.append(case.label)
        for value, color, marker in (
            (case.pinn_property_relative_rmse, PHYSICS, "o"),
            (case.conventional_property_relative_rmse, CONVENTIONAL, "s"),
        ):
            if value is None:
                continue
            axis.plot(position, 100 * value, marker=marker, markersize=9,
                      color=color, markeredgecolor="white", markeredgewidth=0.7,
                      zorder=3)
        if case.pinn_property_relative_rmse is not None:
            axis.annotate(
                f"{100 * case.pinn_property_relative_rmse:.2f}%",
                (position, 100 * case.pinn_property_relative_rmse),
                xytext=(0, 11), textcoords="offset points", ha="center",
                color=PHYSICS, fontsize=9.5,
            )
        else:
            axis.annotate(
                "no fit\nattempted", (position, 3.0), ha="center",
                color=MUTED, fontsize=9.5, va="center",
            )
        verdict = "permitted" if case.permitted else "REJECTED"
        axis.annotate(
            f"rank {case.supported_rank}/{case.coefficient_count}\n{verdict}",
            (position, 0.55), ha="center", va="bottom", fontsize=9.5,
            color=INK if case.permitted else DATA_ONLY,
            fontweight="bold" if not case.permitted else "normal",
        )
    axis.set_yscale("log")
    axis.set_xticks(range(len(order)), labels)
    axis.set_xlim(-0.5, len(order) - 0.5)
    axis.set_ylim(0.5, 220)
    axis.grid(axis="x", visible=False)
    axis.set_ylabel("Post-fit property-curve error (%)")
    axis.legend(
        handles=[
            Line2D([], [], color=PHYSICS, marker="o", linestyle="none",
                   markersize=8, label="Inverse PINN"),
            Line2D([], [], color=CONVENTIONAL, marker="s", linestyle="none",
                   markersize=8, label="Conventional fit"),
        ],
        loc="upper right", frameon=False, fontsize=9.5,
    )


def save_pinn_trust_figure(story: PinnTrustStory, output: Path | str) -> Path:
    """Save the four-panel physics-informed evidence and limits figure."""

    destination = Path(output).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    figure = Figure(figsize=(15.4, 12.0), facecolor="white")
    FigureCanvasAgg(figure)
    axes = figure.subplots(2, 2)
    figure.subplots_adjust(
        left=0.145, right=0.975, top=0.785, bottom=0.205,
        wspace=0.42, hspace=0.82,
    )
    figure.text(
        0.052, 0.955, "What the physics buys, and what it cannot promise",
        fontsize=25, fontweight="bold", color=INK,
    )
    figure.text(
        0.052, 0.921,
        "Four synthetic studies  |  identical network sizes where compared  |  "
        "every value read back from stored results",
        fontsize=13, color=MUTED,
    )
    figure.legend(
        handles=[
            Line2D([], [], color=PHYSICS, marker="o", linestyle="none",
                   markersize=9, label="Physics-informed network"),
            Line2D([], [], color=DATA_ONLY, marker="^", linestyle="none",
                   markersize=9, label="Data-only network"),
            Line2D([], [], color=CONVENTIONAL, marker="s", linestyle="none",
                   markersize=9, label="Conventional estimator"),
        ],
        loc="upper left", bbox_to_anchor=(0.048, 0.892), ncol=3, frameon=False,
        fontsize=11.5, handletextpad=0.4, columnspacing=2.2,
    )
    for axis in axes.flat:
        _style_axis(axis)

    _heading(
        axes[0, 0], "1.  Fitting the data is not learning the system",
        f"Two {story.trainable_parameters:,}-parameter networks, same "
        f"{story.retained_observations} noisy rows, {story.removed_observations} removed",
    )
    _heading(
        axes[0, 1], "2.  It survives a different truth model",
        f"Truth uses another grid, integrator and property basis  |  "
        f"{story.mismatch_trials} paired trials",
    )
    _heading(
        axes[1, 0], "3.  A falling loss does not mean converged physics",
        f"{story.audit_trials} seeds per budget  |  observation loss rises while "
        "the physics improves",
    )
    _heading(
        axes[1, 1], "4.  A good fit cannot prove sufficiency",
        "Rank is measured before fitting  |  error is measured after",
    )

    _plot_reconstruction(axes[0, 0], story)
    _plot_mismatch(axes[0, 1], story)
    _plot_audit(axes[1, 0], story)
    _plot_sufficiency(axes[1, 1], story)

    figure.text(
        0.052, 0.118,
        "Embedding the governing equations recovers states no sensor saw and "
        "keeps the energy books, and it holds when the truth is a different model.",
        fontsize=13, color=INK,
    )
    figure.text(
        0.052, 0.091,
        "But neither the loss curve nor the quality of the fit can tell you the "
        "physics converged or the measurements were sufficient. Separate gates do that.",
        fontsize=13, color=INK,
    )
    for offset, note in enumerate(
        (
            "Panel 1 is one physics-informed against one data-only network of "
            "identical size, not a general claim about architectures. Data-only "
            "trains faster and fits the given noisy rows slightly better.",
            "Panel 3's operational gate is truth-blind; curve shape is scored "
            "against the declared truth. Passing the first does not imply the second.",
            "Panel 4's rank gate is local and uses the declared synthetic noise "
            "model. All four studies are synthetic, so none of this is hardware "
            "identifiability.",
        )
    ):
        figure.text(0.052, 0.055 - 0.023 * offset, note, fontsize=10.5, color=MUTED)
    figure.savefig(destination, dpi=170)
    return destination


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Render the combined physics-informed evidence and limits figure."
    )
    for key, (filename, walkthrough) in SOURCE_FIGURES.items():
        parser.add_argument(
            f"--{key}", type=Path,
            default=default_figure_path(filename, walkthrough),
            help=f"sidecar for the {key} study",
        )
    parser.add_argument("--output", type=Path, default=DEFAULT_PINN_TRUST_PATH)
    arguments = parser.parse_args(argv)
    story = build_pinn_trust_story(
        _load(arguments.reconstruction),
        _load(arguments.mismatch),
        _load(arguments.audit),
        _load(arguments.sufficiency),
    )
    print(format_pinn_trust_report(story))
    figure_path = save_pinn_trust_figure(story, arguments.output)
    save_figure_data(
        {
            "ratios": [item._asdict() for item in story.ratios],
            "mismatch": [item._asdict() for item in story.mismatch],
            "audit": [item._asdict() for item in story.audit],
            "sufficiency": [item._asdict() for item in story.sufficiency],
        },
        figure_path,
    )
    save_figure_explanation(
        figure_path, explanation=FIGURE_EXPLANATION, walkthrough=WALKTHROUGH
    )
    print(f"figure: {figure_path}")


if __name__ == "__main__":
    main()
