"""ThermoTwin physics models."""

from .core.controls import PiecewiseConstantCurrent
from .numerics.integration import IntegrationDivergenceError

from .physics.four_node import (
    FourNodeContactSteadyState,
    FourNodeContactTemperatureRates,
    FourNodeContactTemperatureTrajectory,
    FourNodeContactThermalParameters,
    four_node_contact_rhs,
    four_node_contact_steady_state,
    four_node_contact_steady_state_from_current_moments,
    integrate_four_node_contact,
    thermal_contact_heat,
)

from .simulation.four_node_diagnostics import (
    ContactTrajectoryDiagnostics,
    evaluate_contact_trajectory,
)

from .simulation.four_node_experiments import (
    ContactExperimentResult,
    FourNodeContactExperiment,
    constant_current_contact_reference_experiment,
    run_four_node_contact_experiment,
)

from .physics.two_node import (
    SteadyStateTemperatures,
    TemperatureRates,
    TemperatureTrajectory,
    TwoNodeThermalParameters,
    integrate_two_node,
    two_node_rhs,
    two_node_steady_state,
)

from .physics.thermoelectric import (
    ThermoelectricParameters,
    coefficient_of_performance,
    cold_side_heat,
    conductive_heat_leak,
    electrical_power,
    hot_side_heat,
    heating_coefficient_of_performance,
    joule_heating,
    peltier_heat,
    voltage,
)

from .simulation.two_node_diagnostics import TrajectoryDiagnostics, evaluate_trajectory

from .simulation.two_node_experiments import (
    ExperimentResult,
    TwoNodeExperiment,
    constant_current_reference_experiment,
    run_two_node_experiment,
)

from .observations.test_stand import (
    IdealTemperatureSensor,
    IdealVirtualTestStand,
    ObservationDataset,
    TemperatureObservation,
    TemperatureSensorLocation,
    ideal_four_sensor_test_stand,
    observe_contact_trajectory,
    regular_measurement_times,
    run_ideal_contact_reference_test_stand,
)

from .observations.metadata import (
    ContactExperimentMetadata,
    CurrentScheduleMetadata,
    DatasetProvenance,
    MetadataSetting,
    ObservationProcessStep,
)

from .observations.noise import (
    GaussianTemperatureNoise,
    TemperatureNoiseResult,
    apply_gaussian_temperature_noise,
    reference_gaussian_temperature_noise,
    run_noisy_contact_reference_test_stand,
)

from .observations.bias import (
    FixedTemperatureBias,
    NoisyBiasedTemperatureResult,
    TemperatureBiasResult,
    apply_fixed_temperature_bias,
    reference_fixed_temperature_bias,
    run_biased_contact_reference_test_stand,
    run_noisy_biased_contact_reference_test_stand,
)

from .observations.lag import (
    FirstOrderTemperatureLag,
    LaggedNoisyBiasedTemperatureResult,
    TemperatureLagResult,
    apply_first_order_temperature_lag,
    reference_first_order_temperature_lag,
    run_lagged_contact_reference_test_stand,
    run_lagged_noisy_biased_contact_reference_test_stand,
)

from .observations.missingness import (
    DeterministicTemperatureMissingness,
    IncompleteTemperatureResult,
    TemperatureMissingnessResult,
    TemperatureSensorOutage,
    apply_deterministic_temperature_missingness,
    reference_deterministic_temperature_missingness,
    run_incomplete_contact_reference_test_stand,
    run_missing_contact_reference_test_stand,
)

from .observations.hardware import (
    HardwareDataset,
    HardwareDatasetSummary,
    load_hardware_csv,
    summarize_hardware_dataset,
)

from .design.materials import (
    MaterialSample,
    N_TYPE_SAMPLES,
    P_TYPE_SAMPLES,
    STARRYDATA_SNAPSHOT_DOI,
    STARRYDATA_SNAPSHOT_FILENAME,
    STARRYDATA_SNAPSHOT_LICENSE,
    STARRYDATA_SNAPSHOT_MD5,
    STARRYDATA_SNAPSHOT_URL,
    material_sample,
)

from .design.codesign import (
    APPLICATION_SPECIFICATIONS,
    ApplicationSpecification,
    BayesianOptimizationResult,
    CodesignCampaignConfig,
    CodesignCampaignResult,
    DesignOperatingPoint,
    InitialDesignSummary,
    ModuleAssemblyAssumptions,
    ModuleElectricalResistanceComponents,
    ModuleGeometry,
    PropertyMultipliers,
    PrototypeDesign,
    RobustnessResult,
    design_features,
    evaluate_design_current,
    expected_improvement,
    format_codesign_campaign_report,
    gaussian_process_predict,
    generate_space_filling_designs,
    latin_hypercube,
    module_thermoelectric_parameters,
    module_electrical_resistance_components,
    optimize_design_current,
    prototype_cost_index,
    run_bayesian_optimization,
    run_codesign_campaign,
    run_robustness_study,
)

__all__ = [
    "ContactExperimentResult",
    "ContactExperimentMetadata",
    "ContactTrajectoryDiagnostics",
    "DeterministicTemperatureMissingness",
    "CurrentScheduleMetadata",
    "DatasetProvenance",
    "FourNodeContactExperiment",
    "FourNodeContactSteadyState",
    "FourNodeContactTemperatureRates",
    "FourNodeContactTemperatureTrajectory",
    "FourNodeContactThermalParameters",
    "FixedTemperatureBias",
    "FirstOrderTemperatureLag",
    "GaussianTemperatureNoise",
    "IdealTemperatureSensor",
    "IdealVirtualTestStand",
    "IncompleteTemperatureResult",
    "LaggedNoisyBiasedTemperatureResult",
    "MaterialSample",
    "MetadataSetting",
    "ObservationDataset",
    "ObservationProcessStep",
    "NoisyBiasedTemperatureResult",
    "SteadyStateTemperatures",
    "TemperatureRates",
    "TemperatureObservation",
    "TemperatureLagResult",
    "TemperatureMissingnessResult",
    "TemperatureNoiseResult",
    "TemperatureSensorOutage",
    "TemperatureBiasResult",
    "TemperatureSensorLocation",
    "TemperatureTrajectory",
    "ThermoelectricParameters",
    "TrajectoryDiagnostics",
    "ExperimentResult",
    "HardwareDataset",
    "HardwareDatasetSummary",
    "TwoNodeExperiment",
    "TwoNodeThermalParameters",
    "PiecewiseConstantCurrent",
    "IntegrationDivergenceError",
    "APPLICATION_SPECIFICATIONS",
    "ApplicationSpecification",
    "BayesianOptimizationResult",
    "CodesignCampaignConfig",
    "CodesignCampaignResult",
    "DesignOperatingPoint",
    "InitialDesignSummary",
    "ModuleAssemblyAssumptions",
    "ModuleElectricalResistanceComponents",
    "ModuleGeometry",
    "N_TYPE_SAMPLES",
    "P_TYPE_SAMPLES",
    "PropertyMultipliers",
    "PrototypeDesign",
    "RobustnessResult",
    "STARRYDATA_SNAPSHOT_DOI",
    "STARRYDATA_SNAPSHOT_FILENAME",
    "STARRYDATA_SNAPSHOT_LICENSE",
    "STARRYDATA_SNAPSHOT_MD5",
    "STARRYDATA_SNAPSHOT_URL",
    "coefficient_of_performance",
    "apply_gaussian_temperature_noise",
    "apply_fixed_temperature_bias",
    "apply_first_order_temperature_lag",
    "apply_deterministic_temperature_missingness",
    "cold_side_heat",
    "constant_current_contact_reference_experiment",
    "constant_current_reference_experiment",
    "conductive_heat_leak",
    "electrical_power",
    "design_features",
    "evaluate_design_current",
    "expected_improvement",
    "format_codesign_campaign_report",
    "gaussian_process_predict",
    "generate_space_filling_designs",
    "evaluate_trajectory",
    "evaluate_contact_trajectory",
    "four_node_contact_rhs",
    "four_node_contact_steady_state",
    "four_node_contact_steady_state_from_current_moments",
    "hot_side_heat",
    "heating_coefficient_of_performance",
    "integrate_four_node_contact",
    "integrate_two_node",
    "ideal_four_sensor_test_stand",
    "joule_heating",
    "latin_hypercube",
    "material_sample",
    "module_thermoelectric_parameters",
    "module_electrical_resistance_components",
    "optimize_design_current",
    "peltier_heat",
    "observe_contact_trajectory",
    "regular_measurement_times",
    "reference_gaussian_temperature_noise",
    "reference_fixed_temperature_bias",
    "reference_first_order_temperature_lag",
    "reference_deterministic_temperature_missingness",
    "prototype_cost_index",
    "run_bayesian_optimization",
    "run_codesign_campaign",
    "run_robustness_study",
    "run_two_node_experiment",
    "run_four_node_contact_experiment",
    "run_biased_contact_reference_test_stand",
    "run_ideal_contact_reference_test_stand",
    "run_lagged_contact_reference_test_stand",
    "run_lagged_noisy_biased_contact_reference_test_stand",
    "run_incomplete_contact_reference_test_stand",
    "run_missing_contact_reference_test_stand",
    "run_noisy_contact_reference_test_stand",
    "run_noisy_biased_contact_reference_test_stand",
    "load_hardware_csv",
    "summarize_hardware_dataset",
    "thermal_contact_heat",
    "two_node_rhs",
    "two_node_steady_state",
    "voltage",
]
