"""Phase E analysis and calibration protocol, bound to the completed Phase D.

No numerical observation is generated by this module. Calibration execution
requires a separate exact-source CI and disposable-rehearsal gate. Reserved
execution is not authorized by any Phase E entry point.
"""

from __future__ import annotations

from copy import deepcopy
import hashlib
import json
from pathlib import Path
from typing import Mapping

from scipy.stats import binom

from .operating_decision import POLICY_NAMES
from .operating_decision_prospective import prospective_selector_rule_payload
from .operating_decision_prospective_costs import (
    PRIMARY_PROSPECTIVE_COST_SCENARIO, _scenario_payload,
)
from .operating_decision_prospective_phase_d import phase_d_runtime_identity
from .operating_decision_prospective_phase_d6_internal_check import (
    PHASE_D6_SOURCE_PATHS, phase_d6_frozen_selector_rule,
)
from .operating_decision_prospective_phase_d_final_freeze import (
    load_prospective_phase_d_final_freeze,
)
from .operating_decision_prospective_phase_e_analysis import (
    ANALYSIS_VERSION, BOUND_ALPHA, FAMILYWISE_ALPHA, PRIMARY_BOUND_COUNT,
    precision_projection,
)
from .operating_decision_prospective_phase_e_calibration import (
    BLOCK_COVERAGE_TARGET, CALIBRATION_BLOCKS, CALIBRATION_CONFIDENCE,
    CALIBRATION_VERSION, PHASE_E_PROCEDURES, RESERVED_BLOCKS,
    SECONDARY_CLEARANCES_KELVIN, SELECTOR_PROCEDURE, tolerance_rank,
)
from .operating_decision_prospective_pilot import (
    PROSPECTIVE_CALIBRATION_PARTITION, PROSPECTIVE_CAMPAIGN,
    PROSPECTIVE_RESERVED_PARTITION, _digest, _validate_revision, _validate_sha256,
)


PHASE_E_VERSION = "operating_decision_prospective_phase_e_v2"
PHASE_E_DOMAIN = "thermotwin.prospective_phase_e"
PHASE_E_REHEARSAL_PARTITION = "p0_disposable_phase_e_roundtrip_v2"
PHASE_E_PRECISION_ARTIFACT_DIGEST = "c36a0daa723cc247370a60a249cf03d36b2dbd899a1d83db4cd1e132e6162ec8"
PHASE_E_PRECISION_PATH = Path(__file__).resolve().parents[1] / "OPERATING_DECISION_PROSPECTIVE_PHASE_E_PRECISION.json"
PHASE_E_SOURCE_PATHS = tuple(sorted(set(PHASE_D6_SOURCE_PATHS).union({
    "thermotwin/OPERATING_DECISION_PROSPECTIVE_PHASE_D_FINAL_FREEZE.json",
    "thermotwin/OPERATING_DECISION_PROSPECTIVE_PHASE_E_PRECISION.json",
    "thermotwin/studies/operating_decision_prospective_phase_d_final_freeze.py",
    "thermotwin/studies/operating_decision_prospective_phase_e.py",
    "thermotwin/studies/operating_decision_prospective_phase_e_analysis.py",
    "thermotwin/studies/operating_decision_prospective_phase_e_calibration.py",
    "thermotwin/studies/operating_decision_prospective_phase_e_execution.py",
    "thermotwin/reports/operating_decision_prospective_phase_e.py",
})))


def load_phase_e_precision_artifact() -> dict:
    record = json.loads(PHASE_E_PRECISION_PATH.read_bytes())
    material = dict(record)
    digest = material.pop("artifact_digest", None)
    expected = hashlib.sha256(json.dumps(
        material, sort_keys=True, separators=(",", ":"), allow_nan=False,
    ).encode()).hexdigest()
    freeze = load_prospective_phase_d_final_freeze()
    if (digest != PHASE_E_PRECISION_ARTIFACT_DIGEST or digest != expected
        or record["phase_d_final_freeze_artifact_digest"] != freeze["artifact_digest"]
        or record["source_d6_json_sha256"] != freeze["evidence"]["phase_d6"]["json_sha256"]
        or record["precision"]["planned_reserved_blocks"] != RESERVED_BLOCKS):
        raise ValueError("Phase E precision artifact is not the frozen development projection")
    return record


def phase_e_precision_payload() -> dict:
    freeze = load_prospective_phase_d_final_freeze()
    groups = {
        SELECTOR_PROCEDURE: freeze["internal_check_result"]["metrics"]["by"]["truth_family"],
        **{policy: freeze["fixed_policy_comparators"][policy]["by"]["truth_family"]
           for policy in POLICY_NAMES},
    }
    result = precision_projection(groups, reserved_blocks=RESERVED_BLOCKS)
    # A four-worker ideal is a lower estimate, not a promised wall duration.
    cpu_hours = freeze["runtime"]["aggregate_block_cpu_seconds"] / 3600 * CALIBRATION_BLOCKS / 10
    result["compute_projection"] = {
        "source": "closed Phase D6 resource record bound in final Phase D freeze",
        "calibration_block_count": CALIBRATION_BLOCKS,
        "approximate_cpu_hours_per_100_block_partition": cpu_hours,
        "ideal_four_worker_wall_hours": cpu_hours / 4,
        "planning_wall_hours_per_partition": [43, 60],
        "planning_raw_block_archive_bytes": freeze["evidence"]["phase_d6"]["archive_size_bytes"] * 10,
        "final_calibration_summary_indexes_raw_blocks_without_duplicating_them": True,
        "planning_disk_budget_including_disposable_probe_bytes": 2 * 1024**3,
        "wall_projection_includes_no_claim_about_unrecorded_prior_invocations": True,
    }
    result["size_decision"] = (
        "Retain 100 calibration and 100 reserved blocks within the reviewed compute plan. "
        "The conservative simultaneous risk bounds are expected to be inconclusive; "
        "no 2-percentage-point risk noninferiority claim is promised. Do not extend after outcomes."
    )
    return result


def phase_e_protocol_payload(*, source_revision: str, source_manifest_digest: str) -> dict:
    _validate_revision(source_revision)
    _validate_sha256("Phase E manifest", source_manifest_digest)
    freeze = load_prospective_phase_d_final_freeze()
    rank = tolerance_rank(CALIBRATION_BLOCKS)
    precision = load_phase_e_precision_artifact()
    return {
        "schema_version": 1, "protocol_version": PHASE_E_VERSION,
        "source_revision": source_revision, "source_manifest_digest": source_manifest_digest,
        "phase_d_final_freeze_artifact_digest": freeze["artifact_digest"],
        "campaign": PROSPECTIVE_CAMPAIGN,
        "calibration_partition": PROSPECTIVE_CALIBRATION_PARTITION,
        "calibration_block_count": CALIBRATION_BLOCKS,
        "reserved_partition": PROSPECTIVE_RESERVED_PARTITION,
        "reserved_block_count": RESERVED_BLOCKS,
        "disposable_rehearsal_partition": PHASE_E_REHEARSAL_PARTITION,
        "selector_rule": prospective_selector_rule_payload(phase_d6_frozen_selector_rule()),
        "draw_count": 16, "max_unstable_draws_per_source_action": 1,
        "worker_count": 4, "sensor_scenario": "nominal",
        "cost_scenario": _scenario_payload(PRIMARY_PROSPECTIVE_COST_SCENARIO),
        "runtime_identity": phase_d_runtime_identity(),
        "procedures": list(PHASE_E_PROCEDURES),
        "calibration": {
            "protocol_version": CALIBRATION_VERSION,
            "score": "max(0, L-d_action-m_true, m_true-(U+d_action)); failures +infinity",
            "arithmetic": "exact stored binary inputs; upward score and outward endpoint rounding only when needed",
            "block_score": "maximum across all three families, including failures",
            "coverage_target": BLOCK_COVERAGE_TARGET,
            "confidence_target_over_calibration_samples": CALIBRATION_CONFIDENCE,
            "order_statistic_rank": rank,
            "achieved_confidence_per_procedure": float(binom.cdf(rank - 1, CALIBRATION_BLOCKS, .9)),
            "guarantee_is_joint_across_procedures": False,
            "same_standard_and_own_correction_for_each_procedure": True,
            "q_does_not_change_selection_stop_offsets_fits_or_verification": True,
            "infinite_correction_rule": "close as infeasible; do not open reserved",
        },
        "analysis": {
            "protocol_version": ANALYSIS_VERSION,
            "primary_question": "realized diagnostic energy saving while retaining decision quality against every qualifying fixed alternative",
            "max_false_approval_risk_given_approval": .10,
            "min_definitive_decision_coverage": .70,
            "max_coverage_loss_against_fixed": .05,
            "max_false_approval_risk_increase_against_fixed": .02,
            "noninferiority_margins_are_project_choices": True,
            "confidence": {
                "familywise_alpha": FAMILYWISE_ALPHA, "primary_bound_count": PRIMARY_BOUND_COUNT,
                "one_sided_alpha_per_primary_bound": BOUND_ALPHA,
                "risk_method": "family-specific exact Clopper-Pearson; mixture upper=max and lower=min; empty approval group N/A",
                "decision_coverage_method": "mean of three family-specific exact lower bounds",
                "paired_coverage_loss_method": "mean across families of upper fixed-only probability minus lower selector-only probability",
                "paired_energy_method": "one-sided Student t on 100 paired block means; approximate normal sampling interpretation",
                "overall_confidence_is_not_an_exact_energy_guarantee": True,
            },
            "qualifying_fixed_policy": "risk upper <= .10 and decision coverage lower >= .70",
            "comparison_set": "all four reported; primary must pass against every qualifying fixed policy, including dominated ones",
            "frontier": "descriptive nondominated energy/decision-coverage/risk points among qualifying fixed policies; no comparator selection for an easier headline",
            "success_rule": "selector qualifies; at least one fixed policy qualifies; positive energy lower bound, coverage-loss upper <= .05, and risk-increase upper <= .02 against every qualifying fixed policy",
            "empty_qualifying_set": "no strongest-fixed superiority claim",
            "partial_comparisons": "report named comparisons only; no primary success",
            "secondary_final_decision_clearance_grid_kelvin": list(SECONDARY_CLEARANCES_KELVIN),
            "secondary_grid_changes_action_selection": False,
            "secondary_grid_has_confirmatory_inference": False,
            "failed_intervals_covered": False,
            "incomplete_energy_contrast": "N/A; prohibit energy claim; no dropping cases",
        },
        "precision_and_compute": precision["precision"],
        "paired_precision_artifact_digest": precision["artifact_digest"],
        "paired_comparison_projections": precision["paired_comparisons"],
        "generation_gate": {
            "protocol_tests_passed_required": True,
            "exact_source_ci_success_required": True,
            "disposable_numerical_roundtrip_required": True,
            "disposable_exact_scientific_replay_required": True,
            "constructed_100_block_archive_roundtrip_required": True,
            "process_tree_monitor_preflight_required": True,
            "maximum_process_tree_bytes": 4 * 1024**3,
            "calibration_only_after_committed_gate_record": True,
            "reserved_generation_authorized": False,
        },
        "failure_policy": {
            "ordinary_fit_verification_missing_interval": "retain every case; +infinity score; abstain",
            "truth_solver_or_wrong_source_or_material_bug": "record incident; stop interpretation; version full affected campaign before replacement",
            "retry_successful_blocks": False,
            "resume": "only complete blocks with unchanged source/protocol/runtime/content seals; same namespace and seeds for interrupted missing blocks",
        },
    }


def phase_e_protocol_digest(*, source_revision: str, source_manifest_digest: str) -> str:
    return _digest(f"{PHASE_E_DOMAIN}.protocol_v1", phase_e_protocol_payload(
        source_revision=source_revision, source_manifest_digest=source_manifest_digest,
    ))


def validate_phase_e_protocol(payload: Mapping[str, object]) -> dict:
    expected = phase_e_protocol_payload(
        source_revision=payload.get("source_revision"),
        source_manifest_digest=payload.get("source_manifest_digest"),
    )
    if payload != expected:
        raise ValueError("Phase E protocol differs from the frozen analysis design")
    return deepcopy(expected)
